### ISSUE TITLE
unsupported pickle protocol: 3

### ISSUE THREAD

**Issue by naeimrezaeian** [tyz910/sberbank-qa#1]
здравствуйте

при запуске этого файла **predict**  ошибка выдают  **ValueError: unsupported pickle protocol: 3**
вы можете объяснить что за файлы "model/vocab.pickle" , " model/weights.pickle" и как из заново создать

**Comment by tyz910** [comment]
Для запуска нужна 3-я версия питона, а не 2-я.

**Comment by tyz910** [comment]
Еще можно запустить через Docker:
```docker run --rm -it -v $PWD:/app -w /app -p 8888:8888 sberbank/sdsj-python jupyter notebook --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''```

**Comment by naeimrezaeian** [comment]
> Еще можно запустить через Docker:
> `docker run --rm -it -v $PWD:/app -w /app -p 8888:8888 sberbank/sdsj-python jupyter notebook --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''`

не работает!!!!
вы не могли бы шаг за шагом как надо запустить.как будто не хватает файла 

например:
weights_file = 'data/models/drqa-v7-0.774917423379.pt' 

Заранее признателен

**Comment by tyz910** [comment]
Вариант с докером я только что проверил - работает. Проверял на маке, но и на линуксе проблем быть не должно. Приведенная строчка из файла export.ipynb - он использовался для экспорта финальной модели и для запуска решения не нужен, сама модель уже лежит в папке model. Файл .pt можно получить, если самому заново обучить модель через train.ipynb
